version: '3.6'

services:

  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile-prod
    expose:
      - 5000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_prod  
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test  
      - SECRET_KEY=secret_key
    depends_on:  
      - users-db

  users-db:  
    build:
      context: ./services/users/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  client:
    volumes:
      - npm-cache:/root/.npm
    container_name: client
    build:
      context: ./services/client
      dockerfile: Dockerfile-prod
      args:
        - NODE_ENV=production
        - REACT_APP_USERS_SERVICE_URL=http://ec2-35-165-167-88.us-west-2.compute.amazonaws.com
    ports:
      - '3007:80'
    depends_on:
      - users

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: 'no'
    ports:
      - 80:80
    depends_on:
      - users
      - client

volumes:
  npm-cache:
    external: false
