###########
# BUILDER #
###########

# base image
FROM node:10.14.0-alpine as builder

# set working directory
WORKDIR /usr/src/app

# set environment variables
# ENV NODE_ENV development
ENV PATH /usr/src/app/node_modules/.bin:$PATH
ENV REACT_APP_USERS_SERVICE_URL http://localhost

# insall app dependencies
COPY package.json /usr/src/app/package.json
RUN cd /usr/src/app && \
    npm set progress=false && \
    npm config set depth 0 && \
    npm install --only-production react-scripts@latest && \
    npm install --only-productionnpm@latest

# create build
COPY . /usr/src/app
RUN npm run build


#########
# FINAL #
#########

# base image
FROM nginx:1.15.0-alpine

# copy static files
COPY --from=builder /usr/src/app/build /usr/share/nginx/html

# expose port
EXPOSE 80

# run nginx
CMD ["nginx", "-g", "daemon off;"]
