# base image
FROM node:10.14.0-alpine

# set working directory
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

#install and cache app dependencies
COPY package.json /usr/src/app/package.json
RUN mkdir /.npm && chmod 777 /.npm
# Update to latest version so optional dependancies + shrinkwrap work
RUN npm install -g npm@6.4.1
RUN npm install -g react-scripts@latest

# start app
CMD ["npm", "start"]
